version: '3'
services:
  streamlit_test:
    build: .
    restart: always
    working_dir: '/root/app'
    tty: true
    volumes:
      - ./app:/root/app
    ports:
      - 8000:8000
      - 8501:8501
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
volumes:
  mysql_data:

